tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'ldez/tap'
tap 'buildpack/tap'
tap 'teamookla/speedtest'
tap 'dart-lang/dart'

cask_args appdir: "/Applications"

brew 'bash-completion'
brew 'zsh-syntax-highlighting'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'node'
brew 'rust'
brew 'ruby'
brew 'python3'
brew 'openssl'
brew 'openssh'
brew 'tree'
brew 'wget'
brew 'jq'
brew 'fzf'
brew 'diff-so-fancy'
brew 'hugo'
brew 'speedtest'
brew 'dive'
brew 'gh'
brew 'httpie'
brew 'tldr'
brew 'htop'
brew 'wifi-password'
brew 'm-cli'
brew 'dart'

cask 'visual-studio'
cask 'visual-studio-code'
cask 'azure-data-studio'
cask 'slack'
cask 'spotify'
cask 'zoom'
cask 'tunnelblick'
cask 'bitwarden'
cask 'iterm2'
cask 'google-chrome'
cask 'google-drive'
cask 'brave-browser'
cask 'github'
cask 'sourcetree'
cask 'whatsapp'
cask 'telegram-desktop'
cask 'postman'
cask 'ngrok'

# cask 'cyberduck'
# cask 'dotnet-sdk'
# cask 'open-in-code'
# cask 'openinterminal-lite' 
# cask 'dropbox'
# cask 'iriunwebcam'
# cask 'discord'
